package com.zh.file.browser.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class MainForm2 {

    private JPanel mainPanel;
    private JPanel pathPanel;
    private JPanel selectorPanel;
    private JPanel previewPanel;
    private JPanel statusPanel;
    private JButton btn;
    private JLabel rootPathLabel;
    private JList<String> actorSelectList;
    private JList<String> genreSelectList;
    private JLabel statusLabel;
    private JList<ImageIcon> directoryList;
    private JScrollPane directoryScroll;
    private JPanel detailPanel;
    private JLabel idLabel;
    private JLabel castingLabel;
    private JLabel castingDetailLabel;
    private JLabel genreLabel;
    private JLabel genreDetailLabel;
    private JLabel descriptionLabel;
    private JLabel descriptionDetailLabel;
    private JLabel idDetailLabel;

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public JLabel getRootPathLabel() {
        return rootPathLabel;
    }

    public JLabel getStatusLabel() {
        return statusLabel;
    }

    public JList<String> getActorSelectList() {
        return actorSelectList;
    }

    public JList<String> getGenreSelectList() {
        return genreSelectList;
    }

    public JList<ImageIcon> getDirectoryList() {
        return directoryList;
    }

    public JScrollPane getDirectoryScroll() {
        return directoryScroll;
    }

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR call it in your
     * code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(10, 10));
        mainPanel.setMinimumSize(new Dimension(800, 600));
        mainPanel.setPreferredSize(new Dimension(1080, 720));
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null,
            TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        pathPanel = new JPanel();
        pathPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.add(pathPanel, BorderLayout.NORTH);
        pathPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null,
            TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        btn = new JButton();
        btn.setText("Button");
        pathPanel.add(btn, BorderLayout.EAST);
        rootPathLabel = new JLabel();
        rootPathLabel.setText("Path");
        pathPanel.add(rootPathLabel, BorderLayout.WEST);
        selectorPanel = new JPanel();
        selectorPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.add(selectorPanel, BorderLayout.WEST);
        selectorPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null,
            TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        actorSelectList = new JList();
        actorSelectList.setLayoutOrientation(0);
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        defaultListModel1.addElement("init1");
        defaultListModel1.addElement("init2");
        defaultListModel1.addElement("init3");
        actorSelectList.setModel(defaultListModel1);
        selectorPanel.add(actorSelectList, BorderLayout.NORTH);
        genreSelectList = new JList();
        genreSelectList.setLayoutOrientation(0);
        final DefaultListModel defaultListModel2 = new DefaultListModel();
        defaultListModel2.addElement("genre1");
        defaultListModel2.addElement("genre2");
        defaultListModel2.addElement("genre3");
        genreSelectList.setModel(defaultListModel2);
        selectorPanel.add(genreSelectList, BorderLayout.SOUTH);
        final Spacer spacer1 = new Spacer();
        selectorPanel.add(spacer1, BorderLayout.CENTER);
        previewPanel = new JPanel();
        previewPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.add(previewPanel, BorderLayout.CENTER);
        previewPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null,
            TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        directoryList = new JList();
        directoryList.setLayoutOrientation(0);
        directoryList.setMaximumSize(new Dimension(200, 0));
        directoryList.setMinimumSize(new Dimension(200, 0));
        directoryList.setPreferredSize(new Dimension(200, 0));
        directoryList.setSelectionMode(0);
        previewPanel.add(directoryList, BorderLayout.WEST);
        directoryScroll = new JScrollPane();
        directoryScroll.setMaximumSize(new Dimension(18, 0));
        directoryScroll.setMinimumSize(new Dimension(18, 0));
        directoryScroll.setOpaque(false);
        directoryScroll.setPreferredSize(new Dimension(18, 0));
        directoryScroll.setVerticalScrollBarPolicy(22);
        previewPanel.add(directoryScroll, BorderLayout.CENTER);
        detailPanel = new JPanel();
        detailPanel.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        detailPanel.setMinimumSize(new Dimension(600, 101));
        detailPanel.setOpaque(true);
        detailPanel.setPreferredSize(new Dimension(600, 101));
        previewPanel.add(detailPanel, BorderLayout.EAST);
        detailPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null,
            TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        idLabel = new JLabel();
        idLabel.setText("ID");
        detailPanel.add(idLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
            GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        castingLabel = new JLabel();
        castingLabel.setText("Label");
        detailPanel.add(castingLabel,
            new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        castingDetailLabel = new JLabel();
        castingDetailLabel.setText("Label");
        detailPanel.add(castingDetailLabel,
            new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        genreLabel = new JLabel();
        genreLabel.setText("Genre");
        detailPanel.add(genreLabel,
            new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        genreDetailLabel = new JLabel();
        genreDetailLabel.setText("Label");
        detailPanel.add(genreDetailLabel,
            new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        descriptionLabel = new JLabel();
        descriptionLabel.setText("Label");
        detailPanel.add(descriptionLabel,
            new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        descriptionDetailLabel = new JLabel();
        descriptionDetailLabel.setText("Label");
        detailPanel.add(descriptionDetailLabel,
            new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        idDetailLabel = new JLabel();
        idDetailLabel.setText("Label");
        detailPanel.add(idDetailLabel,
            new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        statusPanel = new JPanel();
        statusPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.add(statusPanel, BorderLayout.SOUTH);
        statusPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null,
            TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        statusLabel = new JLabel();
        statusLabel.setText("Loading...");
        statusPanel.add(statusLabel, BorderLayout.WEST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
