package com.zh.file.browser.view;

import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class MainForm2 {

    private JPanel mainPanel;
    private JPanel pathPanel;
    private JPanel selectorPanel;
    private JPanel previewPanel;
    private JPanel statusPanel;
    private JButton btn;
    private JLabel rootPathLabel;
    private JList<String> actorSelectList;
    private JList<String> genreSelectList;
    private JLabel statusLabel;
    private JList directoryList;
    private JLabel previewLabel;

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public JLabel getRootPathLabel() {
        return rootPathLabel;
    }

    public JLabel getStatusLabel() {
        return statusLabel;
    }

    public JList<String> getActorSelectList() {
        return actorSelectList;
    }

    public JList<String> getGenreSelectList() {
        return genreSelectList;
    }

    public JList getDirectoryList() {
        return directoryList;
    }

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR call it in your
     * code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(10, 10));
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null,
            TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        pathPanel = new JPanel();
        pathPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.add(pathPanel, BorderLayout.NORTH);
        pathPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null,
            TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        btn = new JButton();
        btn.setText("Button");
        pathPanel.add(btn, BorderLayout.EAST);
        rootPathLabel = new JLabel();
        rootPathLabel.setText("Path");
        pathPanel.add(rootPathLabel, BorderLayout.WEST);
        selectorPanel = new JPanel();
        selectorPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.add(selectorPanel, BorderLayout.WEST);
        selectorPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null,
            TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        actorSelectList = new JList();
        actorSelectList.setLayoutOrientation(0);
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        defaultListModel1.addElement("init1");
        defaultListModel1.addElement("init2");
        defaultListModel1.addElement("init3");
        actorSelectList.setModel(defaultListModel1);
        selectorPanel.add(actorSelectList, BorderLayout.NORTH);
        genreSelectList = new JList();
        genreSelectList.setLayoutOrientation(0);
        final DefaultListModel defaultListModel2 = new DefaultListModel();
        defaultListModel2.addElement("genre1");
        defaultListModel2.addElement("genre2");
        defaultListModel2.addElement("genre3");
        genreSelectList.setModel(defaultListModel2);
        selectorPanel.add(genreSelectList, BorderLayout.SOUTH);
        final Spacer spacer1 = new Spacer();
        selectorPanel.add(spacer1, BorderLayout.CENTER);
        previewPanel = new JPanel();
        previewPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.add(previewPanel, BorderLayout.CENTER);
        previewPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null,
            TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        directoryList = new JList();
        previewPanel.add(directoryList, BorderLayout.WEST);
        previewLabel = new JLabel();
        previewLabel.setText("Label");
        previewPanel.add(previewLabel, BorderLayout.CENTER);
        statusPanel = new JPanel();
        statusPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.add(statusPanel, BorderLayout.SOUTH);
        statusPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null,
            TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        statusLabel = new JLabel();
        statusLabel.setText("Loading...");
        statusPanel.add(statusLabel, BorderLayout.WEST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
